#!/bin/bash

#Activer les interfaces et mettre les addresses privées 
ip link set dev eth0 up
ip addr add 192.168.106.130/25 dev eth0
ip link set dev eth1 up
ip addr add 1.47.95.129/25 dev eth1

#Routage statique

#Activer le forwarding
#echo 1 > /proc/sys/net/ipv4/ip_forward

#AJouter des routes statiques 
#ip route add 1.47.95.16/28 via 1.47.95.130
#ip route add 1.47.95.32/27 via 1.47.95.130
#ip route add 1.47.95.64/26 via 1.47.95.130

#Configurer le DHCP
#Start le service DHCP
service isc-dhcp-server start

#NAT set up 
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

#La route par défaut
ip route add default via 1.47.95.130

# Ne rien permettre dans un premier temps
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# Ajouter la permission de pinger
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

# Permettre au DHCP de marcher
iptables  -A INPUT -i eth0 -p udp --dport 67:68 --sport 67:68 -j ACCEPT

# Permettere au DNS de marcher
iptables -t filter -A FORWARD -d 1.47.95.18/28 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 1.47.95.18/28 -p udp --sport 53 -j ACCEPT

# permettre au HTTP de marcher
iptables -t filter -A FORWARD -d 1.47.95.20/28 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 1.47.95.20/28 -p tcp --sport 80 -j ACCEPT

# Permettre au FTP de marcher
iptables -A FORWARD -d 1.47.95.19/28 -p tcp --dport 21 -j ACCEPT
iptables -A FORWARD -s 1.47.95.19/28 -p tcp --sport 21 -j ACCEPT
iptables -A FORWARD -p tcp --sport 1024: --dport 1024: -j ACCEPT




