#!/bin/bash
ip link set dev eth0 up
ip addr add 1.47.95.66/26 dev eth0
ip link set dev eth1 up
ip addr add 1.47.95.33/27 dev eth1

#Le routage statique
#echo 1 > /proc/sys/net/ipv4/ip_forward
#ip route add 192.168.106.128/25 via 1.47.95.65
#ip route add 1.47.95.128/25 via 1.47.95.65
#ip route add 1.47.95.16/28 via 1.47.95.34



#Le routage dynamique
service quagga start
sleep 1
