#!/bin/bash
ip link set dev eth0 up
ip addr add 1.47.95.130/25 dev eth0
ip link set dev eth1 up
ip addr add 1.47.95.65/26 dev eth1

#Le routage statique
#echo 1 > /proc/sys/net/ipv4/ip_forward
#ip route add 192.168.106.128/25 via 1.47.95.129
#ip route add 1.47.95.32/27 via 1.47.95.66
#ip route add 1.47.95.16/28 via 1.47.95.66


#Le routage dynamique
service quagga start
sleep 1

